---
- name: crate dirs for {{ runit_service_name }}
  file: >
    dest={{ item }}
    state=directory
  with_items:
    - /etc/sv/{{ runit_service_name }}
    - /etc/sv/{{ runit_service_name }}/log
    - /var/log/runit/{{ runit_service_name }}
  sudo: yes

- name: copy {{ runit_service_name }} run
  template: >
    src=runit_run.j2 dest=/etc/sv/{{ runit_service_name }}/run
    mode=755
  sudo: yes

- name: copy {{ runit_service_name }} log run
  template: >
    src=runit_log_run.j2
    dest=/etc/sv/{{ runit_service_name }}/log/run
    mode=755
  sudo: yes
