---
- name: create user
  user: name={{ deploy_user }} shell=/bin/bash
  sudo: yes
  tags:
    - auth

- name: set up auth key
  authorized_key: >
    user={{ deploy_user }}
    key="{{ item.key }}"
    state={{ item.state }}
  with_items: deploy_user_keys
  sudo: yes
  tags:
    - auth
